name: Lint, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install black
        run: pip install black

      - name: Install autopep8
        run: pip install autopep8

      - name: Install isort
        run: pip install isort

      - name: Install flake8
        run: pip install flake8

      - name: Install pytest
        run: pip install pytest


      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run black
        run: black .
      
      - name: Run autopep8
        run: autopep8 --in-place --aggressive --aggressive . --recursive
      
      - name: Run isort
        run: isort .

      - name: Run flake8
        run: flake8 .

      # - name: Run tests 
      #   run: pytest ./tests
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/toddbot:latest:tag


         